version: "3.8"

services:
  php:
    build: ./docker/php
    volumes:
      - ./api:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    build: ./docker/nginx
    ports:
      - "8081:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - php

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
