<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migración inicial que crea las tablas principales del sistema:
 *  - libro
 *  - usuario
 *  - prestamo
 *
 * Define claves primarias, índices y relaciones entre entidades.
 * Además, establece los campos fecha_prestamo y fecha_devolucion
 * como TIMESTAMP para compatibilidad con PostgreSQL.
 */
final class Version20260305052334 extends AbstractMigration
{
    /**
     * Descripción de la migración.
     */
    public function getDescription(): string
    {
        return 'Creación inicial de tablas con fecha_prestamo y fecha_devolucion como TIMESTAMP para PostgreSQL';
    }

    /**
     * Ejecuta la migración creando las tablas necesarias.
     *
     * @param Schema $schema Esquema de base de datos proporcionado por Doctrine.
     */
    public function up(Schema $schema): void
    {
        // Tabla libro
        $this->addSql('CREATE TABLE libro (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            titulo VARCHAR(255) NOT NULL,
            autor VARCHAR(255) NOT NULL,
            isbn VARCHAR(255) DEFAULT NULL,
            PRIMARY KEY (id)
        )');

        // Tabla usuario
        $this->addSql('CREATE TABLE usuario (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            nombre VARCHAR(255) NOT NULL,
            apellidos VARCHAR(255) NOT NULL,
            dni VARCHAR(15) NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2265B05D7F8F253B ON usuario (dni)');

        // Tabla prestamo
        $this->addSql('CREATE TABLE prestamo (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            fecha_prestamo TIMESTAMP NOT NULL,
            fecha_devolucion TIMESTAMP DEFAULT NULL,
            usuario_id INT NOT NULL,
            libro_id INT NOT NULL,
            PRIMARY KEY (id)
        )');

        // Índices y llaves foráneas
        $this->addSql('CREATE INDEX IDX_F4D874F2DB38439E ON prestamo (usuario_id)');
        $this->addSql('CREATE INDEX IDX_F4D874F2C0238522 ON prestamo (libro_id)');
        $this->addSql('ALTER TABLE prestamo ADD CONSTRAINT FK_F4D874F2DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestamo ADD CONSTRAINT FK_F4D874F2C0238522 FOREIGN KEY (libro_id) REFERENCES libro (id) NOT DEFERRABLE');
    }

    /**
     * Revierte la migración eliminando todas las tablas creadas.
     *
     * @param Schema $schema Esquema de base de datos proporcionado por Doctrine.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE prestamo DROP CONSTRAINT FK_F4D874F2DB38439E');
        $this->addSql('ALTER TABLE prestamo DROP CONSTRAINT FK_F4D874F2C0238522');
        $this->addSql('DROP TABLE prestamo');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE libro');
    }
}